//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyz         0     NONE   float   xy  
// TEXCOORD                 0   xy          1     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float   xyzw
// TEXCOORD                 0   xy          1     NONE   float   xy  
//
vs_5_0
dcl_globalFlags refactoringAllowed | skipOptimization
dcl_input v0.xy
dcl_input v1.xy
dcl_output_siv o0.xyzw, position
dcl_output o1.xy
dcl_temps 2
//
// Initial variable locations:
//   v0.x <- vin.pos.x; v0.y <- vin.pos.y; v0.z <- vin.pos.z; 
//   v1.x <- vin.tex.x; v1.y <- vin.tex.y; 
//   o1.x <- <VS return value>.tex.x; o1.y <- <VS return value>.tex.y; 
//   o0.x <- <VS return value>.pos.x; o0.y <- <VS return value>.pos.y; o0.z <- <VS return value>.pos.z; o0.w <- <VS return value>.pos.w
//
#line 20 "E:\Projects\Project1\Project1\Shaders\Blur\blur.hlsl"
itof r0.zw, l(0, 0, 0, 1)  // r0.z <- vout.pos.z; r0.w <- vout.pos.w
mov r0.xy, v0.xyxx  // r0.x <- vout.pos.x; r0.y <- vout.pos.y

#line 21
mov r1.xy, v1.xyxx  // r1.x <- vout.tex.x; r1.y <- vout.tex.y

#line 23
mov o0.xyzw, r0.xyzw
mov o1.xy, r1.xyxx
ret 
// Approximately 6 instruction slots used
