//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// gTex                              texture  float4          2d             t0      1 
// gOutput                               UAV  float4          2d             u0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed | skipOptimization
dcl_resource_texture2d (float,float,float,float) t0
dcl_uav_typed_texture2d (float,float,float,float) u0
dcl_input vThreadID.xy
dcl_temps 3
dcl_thread_group 256, 1, 1
//
// Initial variable locations:
//   vThreadIDInGroup.x <- groupThreadID.x; vThreadIDInGroup.y <- groupThreadID.y; vThreadIDInGroup.z <- groupThreadID.z; 
//   vThreadID.x <- dispatchThreadID.x; vThreadID.y <- dispatchThreadID.y; vThreadID.z <- dispatchThreadID.z
//
#line 10 "E:\Projects\Project1\Project1\Shaders\Blur\blur_cs.hlsl"
mov r0.x, vThreadID.x  // r0.x <- dispatch_x

#line 11
mov r1.yzw, vThreadID.yyyy  // r1.w <- dispatch_y

#line 12
mov r0.y, r1.w
mov r0.zw, l(0,0,0,0)
ld_indexable(texture2d)(float,float,float,float) r2.xyzw, r0.xyzw, t0.xyzw  // r2.x <- color.x; r2.y <- color.y; r2.z <- color.z; r2.w <- color.w

#line 26
mov r1.x, r0.x
store_uav_typed u0.xyzw, r1.xyzw, r2.xyzw

#line 27
ret 
// Approximately 8 instruction slots used
